source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/variables.conf

# 






# Ambxst
source = ~/.local/share/ambxst/hyprland.conf
# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/decoration.conf
source = ~/.config/hypr/hyprland/animations.conf


#HELLO WORLD