

#Track Pad Gestures
gesture = 4, horizontal, workspace
gesture = 3, pinch,float
gesture = 3, swipe,move



general {


    border_size = 1
    resize_on_border = true
    hover_icon_on_border = false
}


#dwindle layout
dwindle{

    force_split = 2
    preserve_split = true
    # smart_split = true

    special_scale_factor = 0.95
    pseudotile = true
}


misc {

    disable_hyprland_logo = true
    focus_on_activate = true
}

# debug{

# overlay = true

# }