
# Picture-in-Picture
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, keep_aspect_ratio on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, move (monitor_w*.73) (monitor_h*.72)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, size (monitor_w*.25) (monitor_h*.25)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, pin on

# Screen sharing
windowrule = match:title .*is sharing (a window|your screen).*, float on
windowrule = match:title .*is sharing (a window|your screen).*, pin on
windowrule = match:title .*is sharing (a window|your screen).*, move (monitor_w*.5-window_w*.5) (monitor_h-window_h-12)

# --- Tearing ---
windowrule = match:title .*\.exe, immediate on
windowrule = match:title .*minecraft.*, immediate on
windowrule = match:class ^(steam_app).*, immediate on


# Scrolling layout
# bind = $mainMod, period, layoutmsg, move +col
# bind = $mainMod, comma, layoutmsg, move -col
bind = $mainMod SHIFT, right, layoutmsg, swapcol r
bind = $mainMod SHIFT, left, layoutmsg, swapcol l

bind = $mainMod CTRL, left, exec, hyprctl --batch "dispatch movewindow l ; dispatch movewindow d"
bind = $mainMod CTRL, right, exec, hyprctl --batch "dispatch movewindow r ; dispatch movewindow u"
bind = $mainMod CTRL, up, swapwindow, u
bind = $mainMod CTRL, down, swapwindow, d
bind = $mainMod CTRL, p, layoutmsg, promote

windowrule = match:class kitty , opacity 0.8


windowrule {

    name = kitty spawn size
    match:class = kitty
    size = 969 587

}

windowrule {
    name = steam-dedicated-workspace
    match:class = steam
    workspace = 7
    float = on
    persistent_size = true

}



