
# Picture-in-Picture
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, keep_aspect_ratio on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, move (monitor_w*.73) (monitor_h*.72)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, size (monitor_w*.25) (monitor_h*.25)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, pin on

# Screen sharing
windowrule = match:title .*is sharing (a window|your screen).*, float on
windowrule = match:title .*is sharing (a window|your screen).*, pin on
windowrule = match:title .*is sharing (a window|your screen).*, move (monitor_w*.5-window_w*.5) (monitor_h-window_h-12)

# --- Tearing ---
windowrule = match:title .*\.exe, immediate on
windowrule = match:title .*minecraft.*, immediate on
windowrule = match:class ^(steam_app).*, immediate on


# windowrule = match:class kitty , opacity 0.8
workspace = 2, match:class code

windowrule {
    name = Floated workspace
    match:workspace = r[1-2]
    # border_color = rgb(000BCF) rgb(1100BB)
    float = true
    persistent_size = on
    move = (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5))

    # move = 1000 500
}

windowrule {
    name = pseudoworkspace-Test
    match:workspace = 3

    pseudo = true
    persistent_size = on
    # border_color = rgb(9099AC) rgb(AABBC6)
}

windowrule {

    name = kitty spawn size
    match:class = kitty
    size = 969 587

}

# windowrule {
#     name = btop-specific
#     match:title = btop
#     border_color = rgb(FFFFFF) rgb(00AACB) 45deg
#     min_size = 1600 1000
#     dim_around = on
    
# }




# windowrule = float on, match:workspace 3
# windowrule = match:class discord, opacity 0.8
# windowrule = match:class zen, opacity 
# windowrule = match:class code, opacity 0.9

# windowrule = match:title btop ~, float on